# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [32]:
### [your code here]
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [33]:
### [your code here]
print(np.__version__)

2.4.6


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [34]:
### [your code here]
## a = np.random.randint(0, 100, (2, 3, 5))
## a = np.random.rand(2, 3, 5)
a = np.random.random((2, 3, 5))



### 4. Print a.


In [35]:
### [your code here]
print(a)

[[[0.24534725 0.95920872 0.53793175 0.21672746 0.25457382]
  [0.70947131 0.03694285 0.33363593 0.85134043 0.54229652]
  [0.78493328 0.66952303 0.02898162 0.03655408 0.28356008]]

 [[0.01974269 0.218821   0.6510922  0.42391281 0.4972708 ]
  [0.79024118 0.16294768 0.72811384 0.14645429 0.70139102]
  [0.456235   0.6120313  0.16245153 0.79300034 0.99537651]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [36]:
### [your code here]
b = np.ones((5, 2, 3))


### 6. Print b.


In [37]:
### [your code here]
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [38]:
### [your code here]
print(a.size == b.size)
print(a.size, b.size)

True
30 30



### 8. Are you able to add a and b? Why or why not?


In [39]:
### [your code here]
try: 
    a + b
except ValueError as e:
    print(f"Error: {e}")

Error: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 




### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [41]:
### [your code here]
c = b.transpose(1, 2, 0)
print(c.shape)

(2, 3, 5)



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [42]:
### [your code here]
d = a + c


### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [44]:
### [your code here]
print(a)
print(d)


[[[0.24534725 0.95920872 0.53793175 0.21672746 0.25457382]
  [0.70947131 0.03694285 0.33363593 0.85134043 0.54229652]
  [0.78493328 0.66952303 0.02898162 0.03655408 0.28356008]]

 [[0.01974269 0.218821   0.6510922  0.42391281 0.4972708 ]
  [0.79024118 0.16294768 0.72811384 0.14645429 0.70139102]
  [0.456235   0.6120313  0.16245153 0.79300034 0.99537651]]]
[[[1.24534725 1.95920872 1.53793175 1.21672746 1.25457382]
  [1.70947131 1.03694285 1.33363593 1.85134043 1.54229652]
  [1.78493328 1.66952303 1.02898162 1.03655408 1.28356008]]

 [[1.01974269 1.218821   1.6510922  1.42391281 1.4972708 ]
  [1.79024118 1.16294768 1.72811384 1.14645429 1.70139102]
  [1.456235   1.6120313  1.16245153 1.79300034 1.99537651]]]



### 12. Multiply a and c. Assign the result to e.


In [45]:
### [your code here]
e = a * c




### 13. Does e equal to a? Why or why not?


In [46]:
### [your code here]
print(a == e)


[[[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]

 [[ True  True  True  True  True]
  [ True  True  True  True  True]
  [ True  True  True  True  True]]]


In [47]:
print(np.array_equal(a, e))

True




### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [48]:
### [your code here]
d_max = d.max()
d_min = d.min()
d_mean = d.mean()



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [49]:
### [your code here]
f = np.empty(d.shape)




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [56]:
### [your code here]
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if d[i, j, k] == d_min:
                f[i, j, k] = 0
            elif d[i, j, k] == d_max:
                f[i, j, k] = 100
            elif d[i, j, k] < d_mean:
                f[i, j, k] = 25
            elif d[i, j, k] == d_mean:
                f[i, j, k] = 50
            else:
                f[i, j, k] = 75





### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [57]:
print(d_max)
print(d_min)
print(d_mean)

1.9953765070175784
1.0197426874252873
1.46167034375529


In [58]:
### [your code here]
print(d)
print(f)

[[[1.24534725 1.95920872 1.53793175 1.21672746 1.25457382]
  [1.70947131 1.03694285 1.33363593 1.85134043 1.54229652]
  [1.78493328 1.66952303 1.02898162 1.03655408 1.28356008]]

 [[1.01974269 1.218821   1.6510922  1.42391281 1.4972708 ]
  [1.79024118 1.16294768 1.72811384 1.14645429 1.70139102]
  [1.456235   1.6120313  1.16245153 1.79300034 1.99537651]]]
[[[ 25.  75.  75.  25.  25.]
  [ 75.  25.  25.  75.  75.]
  [ 75.  75.  25.  25.  25.]]

 [[  0.  25.  75.  25.  75.]
  [ 75.  25.  75.  25.  75.]
  [ 25.  75.  25.  75. 100.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [ ]:
### [your code here]